name: UnitTest

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  unit-test:
    name: unit-test-jdk-${{ matrix.version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [17, 21]
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.version }}

      - name: Cache m2 repo
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-${{ matrix.version }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.version }}-maven-

      - name: Validate with Maven
        run: mvn test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}